### ISSUE TITLE
demo 工程跑不起来

### ISSUE THREAD

**Issue by peicode** [CCVideo/CloudClass_iOS_Module_SDK#1]
CCStreamerBasic 这个类 里面很多方法都没有

**Comment by qzn928** [comment]
> CCStreamerBasic 这个类 里面很多方法都没有
请直接在releases中下载，因为git对文件大小限制，无法直接提交代码
https://github.com/CCVideo/CloudClass_iOS_Module_SDK/releases/tag/V5.1.2
